services:
  # 1. Flask Backend Web Service (Dockerized with background Hardhat Node)
  - type: web
    name: bchain-access-backend
    env: docker
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true

  # 2. Static Frontend Website
  - type: web
    name: bchain-access-frontend
    runtime: static
    staticPublishPath: frontend
